#!/bin/sh

SRCDIR=/root/Xyce-7.8
ARCHDIR=/root/XyceLibs/Serial

$SRCDIR/configure \
ARCHDIR=$ARCHDIR \
--disable-verbose_linear \
--disable-verbose_nonlinear \
--disable-verbose_time \
--enable-shared \
--enable-xyce-shareable \
CC=gcc \
CXX=g++ \
F77=gfortran \
CXXFLAGS="-O1 -fno-inline -std=c++11"
